PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?URI a ex:Caster;
} 

FROM <file:casters.csv> 
WHERE {
  BIND (URI(CONCAT('http://ex.org/worlds_2019_casters/', ?caster)) AS ?URI)
}
