PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
	?URI a ex:Player;
		ex:name	?player_name;
		ex:position	?player_position;
		ex:team	?player_team;
}

FROM <file:players.csv> 
WHERE {
  BIND (URI(CONCAT('http://ex.org/players/', xsd:string(?player))) AS ?URI)
  BIND (xsd:string(?name) AS ?player_name)
  BIND (xsd:string(?position) AS ?player_position)
  BIND (xsd:string(?team) AS ?player_team)
}