PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
	?URI a ex:Player_stats_per_match;
		ex:name	?player_name;
		ex:match_date ?match_date;
		ex:match_side ?match_side;
		ex:player_position	?player_position;
		ex:player_team	?player_team;
		ex:player_champion	?player_champion;
		ex:team_ban_1	?ban_1;
		ex:team_ban_2	?ban_2;
		ex:team_ban_3	?ban_3;
		ex:team_ban_4	?ban_4;
		ex:team_ban_5	?ban_5;
		ex:game_length ?game_length;
		ex:match_result ?match_result;
		ex:kills ?kills;
		ex:deaths ?deaths;
		ex:assists ?assists;
		ex:team_kills ?team_kills;
		ex:team_deaths ?team_deaths;
		ex:double_kills ?double_kills;
		ex:triple_kills ?triple_kills;
		ex:quadra_kills ?quadra_kills;
		ex:penta_kills ?penta_kills;
		ex:first_blood ?first_blood;
		ex:first_blood_assist	?first_blood_assist;
		ex:first_blood_victim	?first_blood_victim;
		ex:first_blood_time ?first_blood_time;
		ex:first_death	?first_death;
		ex:first_death_time	?first_death_time; 
		ex:team_drag_kills ?team_drag_kills;
		ex:team_elders	?team_elders;
		ex:team_herald	?team_herald;
		ex:herald_time ?herald_time;
		ex:first_tower	?first_tower;
		ex:first_tower_time	?first_tower_time;
		ex:first_mid_tower	?first_mid_tower;
		ex:first_three_tower	?first_three_tower;
		ex:team_tower_kills	?team_tower_kills;
		ex:first_baron	?first_baron;
		ex:first_baron_time	?first_baron_time; 
		ex:team_baron_kills	?team_baron_kills;
		ex:damage_to_champs	?damage_to_champs;
		ex:total_gold	?total_gold;
		ex:minion_kills	?minion_kills;
		ex:monster_kills	?monster_kills;
}

FROM <file:players_stats_per_match.csv> 
WHERE {
  BIND (URI(CONCAT('http://ex.org/players_stats_per_match/', xsd:string(?player))) AS ?URI)
  BIND (xsd:string(?name) AS ?player_name)
	BIND (xsd:date(?date) AS ?match_date)
	BIND (xsd:string(?side) AS ?match_side)
	BIND (xsd:string(?position) AS ?player_position)
	BIND (xsd:string(?team) AS ?player_team)
	BIND (xsd:string(?champion) AS ?player_champion)
	BIND (xsd:string(?ban1) AS ?ban_1)
	BIND (xsd:string(?ban2) AS ?ban_2)
	BIND (xsd:string(?ban3) AS ?ban_3)
	BIND (xsd:string(?ban4) AS ?ban_4)
	BIND (xsd:string(?ban5) AS ?ban_5)
	BIND (xsd:float(?gamelength) AS ?game_length)
	BIND (xsd:boolean(?result) AS ?match_result)
	BIND (xsd:integer(?k) AS ?kills)
	BIND (xsd:integer(?d) AS ?deaths)
	BIND (xsd:integer(?a) AS ?assists)
	BIND (xsd:integer(?teamkills) AS ?team_kills)
	BIND (xsd:integer(?teamdeaths) AS ?team_deaths)
	BIND (xsd:integer(?doubles) AS ?double_kills)
	BIND (xsd:integer(?triples) AS ?triple_kills)
	BIND (xsd:integer(?quadras) AS ?quadra_kills)
	BIND (xsd:integer(?pentas) AS ?penta_kills)
	BIND (xsd:integer(?fb) AS ?first_blood)
	BIND (xsd:integer(?fbassist) AS ?first_blood_assist)
	BIND (xsd:integer(?fbvictim) AS ?first_blood_victim)
	BIND (xsd:float(?fbtime) AS ?first_blood_time)
	BIND (xsd:integer(?fd) AS ?first_death)
	BIND (xsd:float(?fdtime) AS ?first_death_time) 
	BIND (xsd:integer(?teamdragkills) AS ?team_drag_kills)
	BIND (xsd:integer(?elders) AS ?team_elders)
	BIND (xsd:integer(?herald) AS ?team_herald)
	BIND (xsd:float(?heraldtime) AS ?herald_time)
	BIND (xsd:integer(?ft) AS ?first_tower)
	BIND (xsd:float(?fttime) AS ?first_tower_time)
	BIND (xsd:integer(?firstmidouter) AS ?first_mid_tower)
	BIND (xsd:integer(?firsttothreetowers) AS ?first_three_tower)
	BIND (xsd:integer(?teamtowerkills) AS ?team_tower_kills)
	BIND (xsd:integer(?fbaron) AS ?first_baron)
	BIND (xsd:integer(?fbarontime) AS ?first_baron_time) 
	BIND (xsd:integer(?teambaronkills) AS ?team_baron_kills)
	BIND (xsd:integer(?dmgtochamps) AS ?damage_to_champs)
	BIND (xsd:integer(?totalgold) AS ?total_gold)
	BIND (xsd:integer(?minionkills) AS ?minion_kills)
	BIND (xsd:integer(?monsterkills) AS ?monster_kills)

  
}